version: '3.7'


services:
  app:
    command: ["npm", "start"]
    ports:
      - 8080:8080
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile