version: '3.7'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: nightlord189/devops-for-programmers-project-lvl1:latest
    command: ["npm", "test"]
    working_dir: /app
    env_file: 
      - .env
    depends_on: 
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: