name: push

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test
        run: make test

      - name: build
        run: make docker-build-prod

      - name: docker login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: docker push
        run: make docker-push